# 端口
#server:
#  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mechanical@LyjQ1anPro%Root
    url: jdbc:mysql://127.0.0.1:3306/mechanical?characterEncoding=UTF-8&allowMultiQueries=true&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root

# 业务资源的域名
file-domain:
  ali-oss-domain: https://mechanical.oss-cn-hangzhou.aliyuncs.com/

pg-app-info:
  app-id: wx8dd96b368530c89d
  app-secret: 427cd0b374b47ccb63350d1cc39a7cab
  mch-id: 111111
  server-ip: 47.99.241.172
  private-key: 1111
  call-back-url: https://prodcar.lanchengyun.com/pay/callback