spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mechanical@LyjQ1an
    url: jdbc:mysql://121.43.166.200:3306/mechanical?characterEncoding=UTF-8&allowMultiQueries=true&useUnicode=true&serverTimezone=Asia/Shanghai
    username: mechanical

pg-app-info:
  app-id: wx8dd96b368530c89d
  app-secret: 427cd0b374b47ccb63350d1cc39a7cab
  mch-id: 1577949261
  server-ip: 116.62.19.123
  private-key: 11112222333344445555666677771234
  call-back-url: https://testcar.lanchengyun.com/pay/callback