DROP TABLE IF EXISTS `car_user`;
CREATE TABLE `car_user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '数据库自增ID',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`is_deleted` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否被删除：1已被删除、0未',
	`head_portrait` VARCHAR(200) NULL DEFAULT '' COMMENT '头像',
	`name` VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
	`nick_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '昵称',
	`sex` TINYINT(2) NULL DEFAULT NULL COMMENT '性别',
	`phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号',
	`openid` VARCHAR(200) NULL DEFAULT NULL COMMENT '微信小程序授权，openid',
	`session_key` VARCHAR(50) NULL DEFAULT NULL COMMENT 'session_key',
	`vip_start_time` DATETIME NULL DEFAULT NULL COMMENT '会员有效开始时间',
	`vip_end_time` DATETIME NULL DEFAULT NULL COMMENT '会员有效截止时间',
	PRIMARY KEY (`id`)
)
COMMENT='车商用户'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
